name: antren

profile: antren

config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["docs"]
asset-paths: ["assets"]

target-path: "target"
packages-install-path: "packages"

clean-targets: ["target"]

vars:
  peak_time_ranges: [5, 15, 30, 60, 300, 600, 1200, 3600]

models:
  +persist_docs:
    relation: true
    columns: true